### ISSUE TITLE
Travis build fails under Xenial

### ISSUE THREAD

**Issue by brunns** [hamcrest/PyHamcrest#107]
As per [Xenial as the default build environment](https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476), in future builds will run on Xenial by default. Right now, PyHamcrest's build [fails on Xenial](https://travis-ci.org/brunns/PyHamcrest/builds/565346024), though it [passes happily enough on Trusty](https://travis-ci.org/brunns/PyHamcrest/builds/565336327). It's the Python 3.4 version which fails.

I see two options - we could drop support for Python 3.4, or we could pin our build to Trusty. Python 3.4 is out of support, so I lean towards dropping that, and earlier versions, but I'd be interested to hear other thoughts.

**Comment by offbyone** [comment]
I think we'd want to cut over to a 2.x series doing that, and if we do so then we'll also drop Python 2 support at the same time. Let's pin for now.

**Comment by brunns** [comment]
I've pinned the 3.4 to trusty, the rest to xenial. Building OK.

**Comment by brunns** [comment]
Working fine now!
