### ISSUE TITLE
`not` doesn't negate matcher result

### ISSUE THREAD

**Issue by FredrikWendt** [hamcrest/PyHamcrest#110]
This works fine:

    assert_that({"test": True}, is_not(has_key("test")))

However, using built-in `not` doesn't:

    assert_that({"test": True}, not(has_key("test")))

Note that both these pass:

    assert_that(None, is_(None))
    assert_that("thing", not(is_(None)))

so I find it very asymmetrical that only the third test here fails:

    assert_that({"test": True}, not has_key("test"))
    assert_that({"test": True}, not(has_key("test")))
    assert_that({"test": True}, is_not(has_key("test")))

I'm using Ubuntu shipped python3-hamcrest (xenial, v 1.8.0-1).

**Comment by brunns** [comment]
`not()` is a built-in function, not a matcher, and we can't make it behave like one. That's why `not_` exists. I'm not sure anything can be done about that.

**Comment by offbyone** [comment]
Correct. Much as we'd like to do this, the language won't allow it.

**Comment by FredrikWendt** [comment]
Ok, thanks. I wasn't aware of `not_`, as it wasn't listed here: https://pyhamcrest.readthedocs.io/en/release-1.8/tutorial/#predefined-matchers under Logical

**Comment by brunns** [comment]
Ah, now I think that missing documentation *is* a defect. I'll take this one. Thanks.
