### ISSUE TITLE
Extra parentheses is breaking assert_that/is_ 

### ISSUE THREAD

**Issue by mvhb** [hamcrest/PyHamcrest#127]
e.g: `assert_that(("a",is_("b")))` is returning True, but if it use `assert_that("a",is_("b"))`, works as expected.

**Comment by offbyone** [comment]
That's because the first one is not the same call; the first one is calling `assert_that()` with one argument that is a tuple, and the second is calling `assert_that(a, b)` where `a` is `"a"` and `b` is `is_("b")`
