### ISSUE TITLE
How to match exception properties?

### ISSUE THREAD

**Issue by bittrance** [hamcrest/PyHamcrest#128]
I have a webapp with helper methods that raises `bottle.HTTPError` and I want to ensure that a raised exception has a `status_code` property, but it seems the calling/raises pair cannot directly assert this? E.g. something like
```
assert_that(
    calling(helper).with_args(broken_input),
    raises(HTTPError, has_properties(status_code=500))
)
```
Am I missing something obvious or is there no way to match structured details of an exception short of manually catching the exception first? 

If this is indeed the case, would you be amenable to a PR implementing `raises(HTTPError, matching=has_properties(status_code=500))` or perhaps `raises(HTTPError).matching(has_properties(status_code=500))`?

**Comment by brunns** [comment]
Yup - `raises `'s 2nd argument is an optional regex, which needs to match the exception message if supplied. 

@offbyone - I think this sounds like a reasonable addition?

**Comment by offbyone** [comment]
I do. If it can be made to work, for sure.

**Comment by bittrance** [comment]
Roger that. I have some experience with writing rspec matchers which seem to follow an implementation style similar to PyHamcrest. I'll see what I can come up with.
