### ISSUE TITLE
Test coverage submission failing

### ISSUE THREAD

**Issue by brunns** [hamcrest/PyHamcrest#135]
As of [build 181](https://coveralls.io/builds/19865788), test coverage doesn't seem to be working. It was fine for [build 180](https://coveralls.io/builds/19865723). It's possible that this is nothing to do with us, though I am suspicious about the [removal of tox from `devel-requirements.txt`](https://github.com/hamcrest/PyHamcrest/commit/68bbc623902e9410924cd8e783c928aaeb9790fb#diff-1c0c79e166e4be2f37975727e20f7cedL2).

**Comment by offbyone** [comment]
This is resolved as of the change to codecov.io
