### ISSUE TITLE
bad type annotation on raises

### ISSUE THREAD

**Issue by keis** [hamcrest/PyHamcrest#137]
awesome to see hamcrest be 561 compatible, however I ran into this issue testing it out. type checking this sample shows an error even though it's calling raises as documented

```
from hamcrest import raises

def typed() -> None:
    raises(TypeError)
```

```
sample.py:4: error: Argument 1 to "raises" has incompatible type "Type[TypeError]"; expected "Exception"
```

I think it's supposed to have `Type[Exception]` and not `Exception`

**Comment by brunns** [comment]
Absolutely right, good catch, thanks.
