### ISSUE TITLE
Please add the tests directory to the sdist tarballs

### ISSUE THREAD

**Issue by eli-schwartz** [hamcrest/PyHamcrest#141]
Downstream users may wish to run the tests to make sure everything works on their version of python / dependencies.

**Comment by brunns** [comment]
Travis runs the tests on all the versions which PyHamcrest supports - see https://travis-ci.org/github/hamcrest/PyHamcrest. Do people need this?

**Comment by offbyone** [comment]
Resolved in #150 and will be included in the next release
