### ISSUE TITLE
describe_to vs describe_mismatch vs describe_match

### ISSUE THREAD

**Issue by dz0** [hamcrest/PyHamcrest#158]
in `BaseMatcher` there are:
 -  `describe_mismatch` (often overriden)
 - `describe_match` (seldom overriden)
https://github.com/hamcrest/PyHamcrest/blob/9063031c1de6aa39c5f0ccc1314220915b31c599/src/hamcres/core/base_matcher.py

in custom matcher example https://github.com/hamcrest/PyHamcrest#writing-custom-matchers there is 
- `describe_to` -- seems bit inconsistent -- as it describes failure, but usually describes matcher itself

I'd expect the example to have sth like this
```python
    ...
    day_as_string = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ]

    def describe_mismatch(self, description):
        description.append_text("calendar date falling on ").append_text(self.day_as_string[self.day])
   
    def describe_to(self, description):
        description.append_text("calendar date on ").append_text(self.day_as_string[self.day])
   
```

**Comment by dz0** [comment]
ps.: py 3.6 allows f-string style -- which is less clumsy
``` description.append_text(f"calendar date on {self.day_as_string[self.day]}")```

**Comment by brunns** [comment]
I think the example in the readme is intentionally pretty minimal. The docs **do** extend to mentioning `describe_mismatch()` - see [Writing Custom Matchers](https://pyhamcrest.readthedocs.io/en/v2.0.2/custom_matchers/).

**Comment by offbyone** [comment]
The README is, per Simon's comment, intentionally minimal and doesn't try to capture the custom matcher authoring case in detail. 

The f-string case is definitely a "we will get around to that at some point" change :)
