### ISSUE TITLE
Pull request CI is currently broken 

### ISSUE THREAD

**Issue by offbyone** [hamcrest/PyHamcrest#198]
pre-commit CI is failing, for one. Possibly related to #194?

**Comment by brunns** [comment]
Possibly https://github.com/actions/setup-python/issues/244 also.

**Comment by brunns** [comment]
Fixed in #199?

**Comment by offbyone** [comment]
Partially. python/mypy#12339 is also involved, and python/mypy#12340 should fix it if merged + released.
