### ISSUE TITLE
anything like a both matcher?

### ISSUE THREAD

**Issue by adrian-herscu** [hamcrest/PyHamcrest#249]
https://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#both(org.hamcrest.Matcher)

**Comment by brunns** [comment]
Does https://pyhamcrest.readthedocs.io/en/latest/matcher_library/logical_matchers.html#all-of do what you want?

**Comment by adrian-herscu** [comment]
> Does https://pyhamcrest.readthedocs.io/en/latest/matcher_library/logical_matchers.html#all-of do what you want?

Looks like `both` is just a matter of style :)

**Comment by offbyone** [comment]
Closing as not-an-issue
