### ISSUE TITLE
PyPI documentation links

### ISSUE THREAD

**Issue by sduthil** [hamcrest/PyHamcrest#50]
Not a code issue, but on the [PyPI page of PyHamcrest](https://pypi.python.org/pypi/PyHamcrest), there are three links to the documentation: 

1. one at the very beginning
2. one in the "More resources" section
3. one in the package metadata, between Author and Homepage

Number 1 and 3 link to an [old version of PyHamcrest (1.6) hosted on pyhosted.org](http://pythonhosted.org//PyHamcrest/), where no newer documentation is available
Number 2 links to a [non-existing version of PyHamcrest (1.7.1) hosted on readthedocs.org](https://pyhamcrest.readthedocs.org/en/V1.7.1/), where the latest documentation is available.

Number 1 is particularly misleading, because it is very visible, being at the beginning of the page, and links to an old version of the documentation, where, for example, the ```matches_regexp``` matcher does not exist.

Could you please fix these three links, so that they link to the latest documentation on readthedocs.org ?

Thanks.

**Comment by offbyone** [comment]
Link 1 and link 3, I have zero idea how to configure. I'll ask around.

Link 2 is under my control, and I've pushed 34e547b9847aac7caf29b206518f96259b317c74 addressing it

**Comment by offbyone** [comment]
This is complicated by the fact that PyPi uploads are failing for me right now. I'll address this when I can get that working.

**Comment by offbyone** [comment]
Link 2 is fixed. I've got to figure out 1 and 3

**Comment by offbyone** [comment]
Fixed with a redirect
