### ISSUE TITLE
pyhamcrest-1.8.2 missing sdist on pypi

### ISSUE THREAD

**Issue by alunduil** [hamcrest/PyHamcrest#51]
I noticed while packaging pyhamcrest that the sdist is not on pypi.  Is this an oversight or by design?

**Comment by offbyone** [comment]
It’s an accident in the sense that for some reason I’m getting 401 errors from PyPi when trying to upload the sdist. It’s slightly annoying.


—
Chris
offbyone on GitHub, offby1 on twitter

**Comment by offbyone** [comment]
There; I sidestepped my release process and got the sdist up. Sorry about the delay.

—
Chris
offbyone on GitHub, offby1 on twitter

**Comment by alunduil** [comment]
No worries, was just checking.  Thanks for the speedy response!
