### ISSUE TITLE
Move chrisr/pybuilder to a separate repo?

### ISSUE THREAD

**Issue by msabramo** [hamcrest/PyHamcrest#58]
I wonder if it makes sense to move `chrisr/pybuilder` out of PyHamcrest to its own GitHub repo? Though you probably developed it for PyHamcrest, I think it is a generally useful tool and it deserves its own repo.

Because the Docker image name is `chrisr/pybuilder` and it took me a bit of time to find the GitHub repo and verify that I had found the right thing (not *that* long, but still).

My thought was that maybe you could make it easier for contributors by:

1. Make a separate `chrisr/pybuilder` (or another name if you prefer) GitHub repo so it matches the name of the Docker container.

2. Link to said GitHub repo from [your blog post](http://ideas.offby1.net/posts/docker-runner-for-tox.html), which was what I stumbled on when Googling for "docker tox".

Thoughts?

**Comment by offbyone** [comment]
I'm happy to do that. Let me hit it when I'm off work and I'll report back here.

**Comment by offbyone** [comment]
This'll have to happen this weekend. I'll take care of it then, sorry.

**Comment by msabramo** [comment]
No worries. Whenever you get a chance. I'm not blocked on it or anything.

**Comment by msabramo** [comment]
Oh and thank you for making it publically available! I was about to build the same thing and then Googled and found your blog post so you saved me a bunch of time! :smile:

**Comment by offbyone** [comment]
Moved to https://github.com/offbyone/pybuilder

**Comment by msabramo** [comment]
Awesome! Thanks!
