### ISSUE TITLE
Clarification/Question Exception Handling

### ISSUE THREAD

**Issue by Govinda-Fichtner** [hamcrest/PyHamcrest#65]
I have the following test and I wonder how I am supposed to test it properly with PyHamcrest:

```
    def test_function_with_one_required_param_missing(self):

        @ParamsValidator(required=['foo'])
        def function_with_params(event, context):
            return [event, context]

        event = {}
        context = LambdaContext()

        assert_that(calling(function_with_params).with_args(event, context), raises(KeyError, "400:Parameter missing."))
```

It seems that this test is always passing no matter what I do in the decorator. If I raise an KeyError exception or not the test is still passing.

**Comment by arpit1997** [comment]
Some key points to remember while you are testing the code.
`assert` statements always gives the error when The computed value of the function or method and value you specified should not match. In you case you are not correctly passing actual value.
The function will raise a key error with some 10 lines of stack trace and you are comparing it with that small phrase.
I would suggest that handle the exception in the code and assign a message to satcktrace. other than the test is perfect. :smile: :smile_cat:

**Comment by brunns** [comment]
I don't think this is an issue, @offbyone, so we can close it.

**Comment by brunns** [comment]
Closing, since there's been no further conversation on this.
