### ISSUE TITLE
Bad naming of `contains` matcher

### ISSUE THREAD

**Issue by tsouvarev** [hamcrest/PyHamcrest#66]
I have a lot of confusion about `contains` matcher, because it seems like `contains` should check if matched sequence contains provided one. But it matches entire sequence. 

Maybe you can add alias, like `matches` or something like that?

**Comment by brunns** [comment]
Would `contains_exactly()` be a good alias?

**Comment by tsouvarev** [comment]
Yes, thank you

**Comment by brunns** [comment]
#90 any good, @tsouvarev?

**Comment by tsouvarev** [comment]
@brunns looks good to me :) feel free to close issue when request will be merged

**Comment by brunns** [comment]
I think this can be closed, @offbyone.
