### ISSUE TITLE
Not catching the SystemExit exception

### ISSUE THREAD

**Issue by danodonovan** [hamcrest/PyHamcrest#73]
`PyHamcrest==1.9.0`

I'm having trouble catching the `SystemExit` exception with `calling, raises`. Example gist

https://gist.github.com/danodonovan/042e1c74ea76cbea39b42f5c8733ede0

Briefly;

    def call_exit():
        raise SystemExit

    assert_that(calling(call_exit), raises(SystemExit))

fails as `SystemExit` is called, rather than caught.

**Comment by brunns** [comment]
I think this can be closed, @offbyone.
