### ISSUE TITLE
When getting a type mismatch in exception, exception details are not provided

### ISSUE THREAD

**Issue by moshez** [hamcrest/PyHamcrest#82]
Example:

```
AssertionError: 
Expected: Expected a callable raising <class 'microcosm_pubsub.errors.SkipMessage'>
     but: <class 'TypeError'> was raised instead
```

This means that I cannot see what the type error actually was, and fix it.
I've traced the problem to https://github.com/hamcrest/PyHamcrest/blob/29d4f9d23dea293a99d9c32ef893cd4a31b5d3f7/src/hamcrest/core/core/raises.py#L60 -- it seems it would be straight forward to add a description there. Would this make sense as a PR?

**Comment by offbyone** [comment]
Definitely.

**Comment by brunns** [comment]
Any good, @moshez?

**Comment by moshez** [comment]
Looks good!
