### ISSUE TITLE
PyHamcrest uses its own deprecated methods

### ISSUE THREAD

**Issue by pjnagel** [hamcrest/PyHamcrest#85]
IsObjectWithProperty.describe_mismatch() and SelfDescribingValue.describe_to() callsBaseDescription.append_value()

BaseDescription.append_value() contains the code:
```
 warnings.warn('Call append_description_of instead of append_value',
                      DeprecationWarning)
```

This is an issue because I am unit-testing my own matchers, so failing matchers are part of a normal test run, and this means I have to filter out 3rd party warnings to make sure my own code does not trip over deprecation warnings.

**Comment by brunns** [comment]
Any good, @pjnagel?

**Comment by pjnagel** [comment]
That fixes it, @brunns

**Comment by brunns** [comment]
We can close this I think, @offbyone.
