### ISSUE TITLE
Travis builds all fail because of the usage of pip --use-mirrors

### ISSUE THREAD

**Issue by offbyone** [hamcrest/PyHamcrest#86]
See, for example, https://travis-ci.org/hamcrest/PyHamcrest/builds/349481150

This should be fixed before we can merge any other PRs.

**Comment by brunns** [comment]
I'll take a look this weekend if no one else gets to it first.

**Comment by brunns** [comment]
There are some other issues with the build - pypy versions and so on. I'll get the build green before raising a PR.

**Comment by brunns** [comment]
See https://github.com/hamcrest/PyHamcrest/pull/87 - any good?
